### ISSUE TITLE
System is not on quicklisp

### ISSUE THREAD

**Issue by can3p** [sanel/magic-ed#1] opened 2016-12-26 00:55 UTC
Hello,

thanks for very useful library! While readme says that system can be retrieved from quicklisp, it's not actually there. Are you planning to actually publish library?

**Comment by sanel** [comment] 2016-12-26 17:49
Hi Dmitry,

Thanks for the comment and report! `README` referred the way to run quicklisp command from `magic-ed` source folder, so it doesn't have to be present on quicklisp repositories.

I'll keep this ticket open and try to publish it to quicklisp. Do you have any quick know-how to do it?

**Comment by can3p** [comment] 2016-12-27 08:57
Hey Sanel,

I think it's a matter of opening an issue in https://github.com/quicklisp/quicklisp-projects
Readme has a link to some tutorials, but it seems like very little work is needed. Here is an example of closed issue - https://github.com/quicklisp/quicklisp-projects/issues/1205

**Comment by alx-a** [comment] 2020-02-05 22:58
With the updated README, users can trivially install magic-ed manually without the need for the quicklisp repository. The issue could  be thus 
a) be considered closed,
b) alternativelly, I volunteer to submit it to quicklisp-projects. It appears there is a  waiting list, so 
c)I propose/volunteer submitting to Ultralisp. https://ultralisp.org/ and ql:quickload will work. 
Please let me know if You want me to move forward with the submission.
Thanks again for this great utility!

**Comment by sanel** [comment] 2020-02-06 08:55
Yes @alxnorden please do :) Thanks!

**Comment by alx-a** [comment] 2020-02-06 10:42
Updated readme and submitted for review, magic-ed is on ultralisp now.
If working as intended, both manual install and quicklisp via ultralisp should be working now.
Instructions testing for clarity and functionality appreciated.

**Comment by sanel** [comment] 2020-02-06 12:46
Thanks! What would be procedure to update it on ultralisp/quicklisp when new version is out?

**Comment by alx-a** [comment] 2020-02-06 12:55
Ultralisp clones from the repo several times a day (when the server is not overwhelmed)
https://ultralisp.org/projects/sanel/magic-ed
Should show timestamp when it checked-in. 

I.e. With ultralisp, nothing needs to be done for updates (outside the usual update project on github)
Just don't change the distro/project url on github, etc, as that will break it until manual project url  update/resubmission to ultralisp. 

Issue submitted to quicklisp
https://github.com/quicklisp/quicklisp-projects/issues/1795

P.S. From QL, updates about once a month and appear to clone from github automatically
Source: http://blog.quicklisp.org/2015/01/getting-library-into-quicklisp.html


With quicklisp, I will post an update when it is available via quicklisp, or if direct actions by Sanel are needed.

**Comment by sanel** [comment] 2020-02-06 19:05
Great! Can I close this ticked or keep it open until is accepted in Quicklisp?

**Comment by alx-a** [comment] 2020-02-06 19:26
I think it can be closed.

I will pull an update to the README when the quicklisp is confirmed working, alternatively start a new ticket if action is required. (asdf might need updates, etc, we'll see)

Update from quicklisp:
 http://report.quicklisp.org/2020-02-06/failure-report/magic-ed.html
I've updated the file in question.

**Closed as completed** 2020-02-07 12:20 UTC
